// ColorBlindQRTypeReader.cs — Reads the player's self-reported colorblind type from a QR
// code (generated by the intake survey app — per the 07/19 team discussion, each type needs
// its own filter, so the flow stays "survey -> QR -> HoloLens scan" rather than one filter
// for everyone) and drives ColorBlindFilterToggle accordingly. Reuses the same
// ARMarkerManager/QR decode path as QRAnchorAligner.cs (multiplayer anchor alignment) since
// that path is already proven working on-device; this just decodes a different payload.
using System;
using Microsoft.MixedReality.OpenXR;
using UnityEngine;
using UnityEngine.XR.ARSubsystems;

[RequireComponent(typeof(ARMarkerManager))]
public class ColorBlindQRTypeReader : MonoBehaviour
{
    [Tooltip("The filter this reader sets the type on and switches on once a valid QR is scanned.")]
    [SerializeField] private ColorBlindFilterToggle filterToggle;

    // TODO: confirm the exact QR payload with whoever on the organizer side builds the intake
    // survey/QR generator (per 07/19 chat, that's 主辦方, not this team) — this prefix is a
    // placeholder guess, not a confirmed contract. Expected full text e.g. "ColorBlindType:Deuteranomalous".
    [Tooltip("Expected QR text prefix from the intake survey app. PLACEHOLDER — confirm real format with the organizer's survey side before relying on this in a live demo.")]
    [SerializeField] private string qrPrefix = "ColorBlindType:";

    [Tooltip("Turns the filter on automatically once a valid type is scanned, instead of waiting for the player to also press the manual toggle button. Keep the manual button working regardless, for self-demo without a printed QR (per Melody: 你們應該就自己 demo，不用找受試者).")]
    [SerializeField] private bool autoEnableOnScan = true;

    [SerializeField] private bool verboseLogging = true;

    public event Action<ColorBlindFilterToggle.ColorBlindType> TypeDetected;

    private ARMarkerManager markerManager;
    private float sessionStartTime;
    private bool hasAppliedType;

    private void Awake()
    {
        markerManager = GetComponent<ARMarkerManager>();

        // Same replay guard as QRAnchorAligner: HoloLens caches QR detections at the OS level
        // across app sessions, so anything "seen" before this session started is a stale
        // cached reading, not a fresh scan of whatever code the player is holding up now.
        sessionStartTime = Time.realtimeSinceStartup;
    }

    private void OnEnable() => markerManager.markersChanged += OnMarkersChanged;
    private void OnDisable() => markerManager.markersChanged -= OnMarkersChanged;

    private void OnMarkersChanged(ARMarkersChangedEventArgs args)
    {
        if (hasAppliedType) return;

        foreach (var marker in args.added)
        {
            TryApply(marker);
            if (hasAppliedType) break;
        }

        if (!hasAppliedType)
        {
            foreach (var marker in args.updated)
            {
                TryApply(marker);
                if (hasAppliedType) break;
            }
        }
    }

    private void TryApply(ARMarker marker)
    {
        if (marker.trackingState == TrackingState.None) return;
        if (marker.lastSeenTime < sessionStartTime) return;

        var decoded = marker.GetDecodedString();
        if (verboseLogging)
        {
            Debug.Log($"[ColorBlindQRTypeReader] marker id={marker.trackableId} decoded='{decoded}'");
        }

        if (string.IsNullOrEmpty(decoded) || !decoded.StartsWith(qrPrefix)) return;

        var typeName = decoded.Substring(qrPrefix.Length).Trim();
        if (!Enum.TryParse(typeName, out ColorBlindFilterToggle.ColorBlindType type))
        {
            Debug.LogWarning($"[ColorBlindQRTypeReader] Unrecognized colorblind type '{typeName}' in QR '{decoded}'.");
            return;
        }

        hasAppliedType = true;
        filterToggle.type = type;

        if (autoEnableOnScan)
        {
            filterToggle.ToggleFilter();
        }

        TypeDetected?.Invoke(type);
        Debug.Log($"[ColorBlindQRTypeReader] Applied colorblind type '{type}' from scanned QR.");
    }
}
